// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXdrlzMnBJfjdzXmiTQensdZT575HmtoE',
    appId: '1:553304998844:web:ccfda626e534a4b7ae21b9',
    messagingSenderId: '553304998844',
    projectId: 'cce-navigation',
    authDomain: 'cce-navigation.firebaseapp.com',
    storageBucket: 'cce-navigation.firebasestorage.app',
    measurementId: 'G-1P7WNHY8XR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArkMAz5TtMiytJoKs7kKYztl7RMZy8V5o',
    appId: '1:553304998844:android:99b81b6e3e5099f9ae21b9',
    messagingSenderId: '553304998844',
    projectId: 'cce-navigation',
    storageBucket: 'cce-navigation.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBqHAn7eLbRMiuc83PMsN7NvbQLyIW04E',
    appId: '1:553304998844:ios:36831003af2a222dae21b9',
    messagingSenderId: '553304998844',
    projectId: 'cce-navigation',
    storageBucket: 'cce-navigation.firebasestorage.app',
    iosBundleId: 'com.cce.cceMap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXdrlzMnBJfjdzXmiTQensdZT575HmtoE',
    appId: '1:553304998844:web:26f6edeb6b06f666ae21b9',
    messagingSenderId: '553304998844',
    projectId: 'cce-navigation',
    authDomain: 'cce-navigation.firebaseapp.com',
    storageBucket: 'cce-navigation.firebasestorage.app',
    measurementId: 'G-KZBLDZ9RMQ',
  );
}
